trigger:
- master
# dummy commit
pool:
  name: centos-vm

steps:
- bash: |
   terraform init
   terraform workspace new dev
   ansible-playbook terraform.yml
  workingDirectory: ansible
  displayName: 'Bash Script'