trigger:
- master

pool:
  name: centos-vm

steps:
- bash: |
   ansible-playbook terraform.yml
  workingDirectory: $(Build.SourcesDirectory)/terraform/az-vm
  displayName: 'Bash Script'

  #  terraform init
  #  terraform workspace new dev