---
- hosts: localhost
  become: yes
  vars:
    state: present
    resource_group_name: "tfrg"
    storage_account_name: "rishtfstate"
    container_name: "tfstatefiles"
    key: "terraform.tfstate"
    app_env: dev
    project_path: "../../terraform/az-vm/"
    ssh_key_path: "/home/vagrant/az-vm-keys/.ssh"
    ssh_key_name: "az-key"
    group_name: "adminuser"
    user_name: "adminuser"
  tasks:
    - name: Create new group
      group:
        name: "{{ group_name }}"
        state: present
    - name: Create new user
      user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"
        state: present
    - name: Create SSH key directory
      file:
        path: "{{ ssh_key_path }}"
        state: directory
        mode: '0700'
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}/{{ ssh_key_name }}"
        group: "{{ group_name }}"
        owner: "{{ user_name }}"
        state: present
        mode: '0600'
    - name: Create Azure SP
      shell: |
        azsp_output=$(az ad sp create-for-rbac --name "devops-projects-sp" --role contributor --scopes /subscriptions/$ARM_SUBSCRIPTION_ID)
        ARM_CLIENT_ID=$( echo $azsp_output | jq '.appId' )
        ARM_CLIENT_SECRET=$( echo $azsp_output | jq '.password' )
        ARM_TENANT_ID = $( echo $azsp_output | jq '.tenant' )
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
    - name: Initialize Terraform backend
      shell: |
        cd {{ project_path }}
        ls -l
        terraform init -backend-config="dev.tfbackend"
    - name: Run terraform validate
      shell: |
        cd {{ project_path }}
        terraform validate
    - name: Run terraform plan
      shell: |
        cd {{ project_path }}
        terraform plan -var-file="{{ app_env }}.tfvars"
    - name: Run terraform scripts
      shell: |
        cd {{ project_path }}
        terraform apply -auto-approve -var-file="{{ app_env }}.tfvars"
