---
- hosts: localhost
  become: yes
  vars:
    state: present
    resource_group_name: "tfrg"
    storage_account_name: "rishtfstate"
    container_name: "tfstatefiles"
    key: "terraform.tfstate"
    app_env: dev
    project_path: "../../terraform/az-vm/"
    ssh_key_path: "/home/vagrant/az-vm-keys/.ssh"
    ssh_key_name: "az-key"
    group_name: "adminuser"
    user_name: "adminuser"
  tasks:
    - name: Create new group
      group:
        name: "{{ group_name }}"
        state: present
    - name: Create new user
      user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"
        state: present
    - name: Create SSH key directory
      file:
        path: "{{ ssh_key_path }}"
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}/{{ ssh_key_name }}"
        group: "{{ group_name }}"
        owner: "{{ user_name }}"
        state: present
        mode: '0600'
