trigger:
  branches:
    include: ['*']
  paths:
    include:
      - 'terraform/az-vm/*'
      - 'cicd/az-devops/az-vm/*'
      - 'ansible/az-vm/*'

pool:
  name: centos-vm
variables:
  app_env: dev
  ssh_key_path: "/home/vagrant/az-vm-keys/.ssh/*.pub"

steps:
# - bash: |
#    ansible-playbook terraform.yml -v
#   workingDirectory: $(Build.SourcesDirectory)/ansible/az-vm
#   displayName: 'Bash Script'

  #  terraform init
  #  terraform workspace new dev
# Azure CLI v2
# Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azspn' 
    scriptType: bash 
    scriptLocation: 'inlineScript'
    inlineScript: 'ansible-playbook terraform.yml; sudo cp $(ssh_key_path) $(Build.SourcesDirectory)/terraform/az-vm; sudo chown vagrant:vagrant $(Build.SourcesDirectory)/terraform/az-vm/*.pub' 
    addSpnToEnvironment: true # boolean. Access service principal details in script. Default: false.
    workingDirectory: $(Build.SourcesDirectory)/ansible/az-vm
    displayName: 'Ansible Playbook'

    #useGlobalConfig: false # boolean. Use global Azure CLI configuration. Default: false.
    #workingDirectory: # string. Alias: cwd. Working Directory. 
    #failOnStandardError: false # boolean. Fail on Standard Error. Default: false.
    #powerShellIgnoreLASTEXITCODE: false # boolean. Optional. Use when scriptType = ps || scriptType = pscore. Ignore $LASTEXITCODE. Default: false.
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azspn' 
    scriptType: bash 
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID; terraform init -backend-config="dev.tfbackend" --reconfigure' 
    addSpnToEnvironment: true # boolean. Access service principal details in script. Default: false.
    workingDirectory: $(Build.SourcesDirectory)/terraform/az-vm
    displayName: 'Terraform Init'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azspn' 
    scriptType: bash 
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform validate; terraform plan -var-file=$(app_env).tfvars' 
    addSpnToEnvironment: true # boolean. Access service principal details in script. Default: false.
    workingDirectory: $(Build.SourcesDirectory)/terraform/az-vm
    displayName: 'Terraform Validate & Plan'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azspn' 
    scriptType: bash 
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform apply -auto-approve -var-file=$(app_env).tfvars' 
    addSpnToEnvironment: true # boolean. Access service principal details in script. Default: false.
    workingDirectory: $(Build.SourcesDirectory)/terraform/az-vm
    displayName: 'Terraform Apply'
    #     - name: Initialize Terraform backend
    #   shell: |
    #     cd {{ project_path }}
    #     az --version
    #     az logout; az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
    #     terraform init -backend-config="dev.tfbackend" --reconfigure
    # - name: Run terraform validate
    #   shell: |
    #     cd {{ project_path }}
    #     
    # - name: Run terraform plan
    #   shell: |
    #     cd {{ project_path }}
    #     "
    # - name: Run terraform scripts
    #   shell: |
    #     cd {{ project_path }}
    #     "