trigger:
  branches:
    include: ['*']
  paths:
    include:
      - 'terraform/az-vm/*'
      - 'cicd/az-devops/az-vm/*'
      - 'ansible/az-vm/*'

pool:
  name: centos-vm

steps:
- bash: |
   ansible-playbook terraform.yml
  workingDirectory: $(Build.SourcesDirectory)/ansible/az-vm
  displayName: 'Bash Script'

  #  terraform init
  #  terraform workspace new dev