trigger:
  branches:
    include: ['*']
  paths:
    include:
      - $(Build.SourcesDirectory)/terraform/az-vm/*
      - 'cicd/az-devops/az-vm/*'

pool:
  name: centos-vm

steps:
- bash: |
   ansible-playbook terraform.yml
  workingDirectory: $(Build.SourcesDirectory)/ansible
  displayName: 'Bash Script'

  #  terraform init
  #  terraform workspace new dev