---
- hosts: localhost
  vars:
    state: present
    resource_group_name: "tfrg"
    storage_account_name: "rishtfstate"
    container_name: "tfstatefiles"
    key: "terraform.tfstate"
    app_env: dev
    project_path: "../terraform/az-vm/"
  tasks:
    - name: Initialize Terraform backend
      shell: |
        terraform init -backend-config="resource_group_name={{ resource_group_name }}" -backend-config="storage_account_name={{ storage_account_name }}" -backend-config="container_name={{ container_name }}"
    - name: Run terraform scripts
      terraform:
        project_path: "{{ project_path }}"
        state: "{{ state }}"
        backend_config:
          resource_group_name: "{{ resource_group_name }}"
          storage_account_name: "{{ storage_account_name }}"
          container_name: "{{ container_name }}"
          key: "{{ key }}"
        variables_file: "{{app_env}}.tfvars"
        # workspace: "{{app_env}}"
