---
- hosts: localhost
  vars:
    state: present
    resource_group_name: "tfrg"
    storage_account_name: "rishtfstate"
    container_name: "tfstatefiles"
    key: "terraform.tfstate"
    app_env: dev
    project_path: "../terraform/az-vm/"
    ssh_key_path: "/home/vagrant/az-vm-keys/.ssh"
    ssh_key_name: "az-key"
  tasks:
    - name: Create SSH key directory
      file:
        path: "{{ ssh_key_path }}"
        state: directory
        mode: '0700'
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ssh_key_path }}/{{ ssh_key_name }}"
        state: present
    - name: Initialize Terraform backend
      shell: |
        cd {{ project_path }}
        terraform init -backend-config="dev.tfbackend"
    - name: Run terraform scripts
      shell: |
        cd {{ project_path }}
        terraform apply -auto-approve -var-file="{{ app_env }}.tfvars"
