---
- hosts: localhost
  vars:
    state: present
    resource_group_name: "tfrg"
    storage_account_name: "rishtfstate"
    container_name: "tfstatefiles"
    key: "terraform.tfstate"
    app_env: dev
    project_path: "../terraform/az-vm/"
  tasks:
    - name: Initialize Terraform backend
      shell: |
        cd {{ project_path }}
        terraform init -backend-config="dev.tfbackend"
    - name: Run terraform scripts
      shell: |
        cd {{ project_path }}
        terraform apply -auto-approve -var-file="{{ app_env }}.tfvars"
